# Generated by Django 5.1.7 on 2025-04-29 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=10, null=True)),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Project Manager', 'Project Manager'), ('Site Engineer', 'Site Engineer'), ('Surveyor', 'Surveyor'), ('ROW Coordinator', 'ROW Coordinator'), ('Quality Inspector', 'Quality Inspector'), ('User', 'User'), ('Viewer', 'Viewer')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('Bihar', 'Bihar'), ('Gujarat', 'Gujarat'), ('UP', 'Uttar Pradesh'), ('Haryana', 'Haryana'), ('Delhi', 'Delhi'), ('Himachal Pradesh', 'Himachal Pradesh'), ('AP', 'Andhra Pradesh'), ('Jharkhand', 'Jharkhand'), ('MP', 'Madhya Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam'), ('Chhattisgarh', 'Chhattisgarh'), ('Goa', 'Goa'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Tamil Nadu', 'Tamil Nadu'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('West Bengal', 'West Bengal')], max_length=100)),
                ('block', models.CharField(choices=[('Block A', 'Block A'), ('Block B', 'Block B'), ('Block C', 'Block C')], max_length=100)),
                ('milestone', models.CharField(choices=[('Desktop Survey Design', 'Desktop Survey Design'), ('Design / Network-Health-Checkup', 'Design / Network-Health-Checkup'), ('HOTO-Existing', 'HOTO-Existing'), ('Detailed Design', 'Detailed Design'), ('ROW(Right of Way)', 'ROW(Right of Way)'), ('IFC(Issued for Comnstruction)', 'IFC(Issued for Comnstruction)'), ('IC(Intial Construction)', 'IC(Intial Construction)'), ('As-Built', 'As-Built'), ('HOTO (Final)', 'HOTO (Final)')], max_length=100)),
                ('business_area', models.CharField(choices=[('Area1', 'Area1'), ('Area2', 'Area2'), ('Area3', 'Area3')], max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('subtasks', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('inprogress', 'Inprogress'), ('nill', 'Nill')], max_length=100)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polycabmanage.user')),
            ],
        ),
    ]
